name: mbtestsite
favicon: null
layout_spectrum: 0.06093027559109032
typography_spectrum: 0.39568474935367703
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#29261d'
    - '#989898'
    - '#887a60'
    - '#beaf98'
  brandStrength: 0.875
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
